# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "foo"
          echo "Lorem ipsum dolor sit amet, consectetur a
          dipisicing elit. Dicta illum maxime totam? A ab accusantium ad aliquam aperiam architecto aspernatur blanditiis consequuntur dicta dolore eius, enim et fuga inventore itaque laboriosam laborum magnam mollitia nesciunt nisi numquam obcaecati omnis perferendis possimus quasi qui quibusdam quidem quo quod recusandae repellat sit suscipit tempore ullam unde vitae voluptate? Amet in nihil nobis quibusdam! Assumenda aut dolor dolore dolores eveniet fuga iusto laboriosam officiis quasi quidem repudiandae, soluta sunt vero. Ab accusamus consequatur cum enim error explicabo ipsum, iusto, minus nostrum omnis quibusdam, quis recusandae reprehenderit sapiente totam! Exercitationem ipsam iste libero molestias non perspiciatis quisquam? Accusamus alias, aspernatur consequatur consequuntur illum iusto nemo qui quidem quis sapiente! Alias ea, unde. Asperiores assumenda consectetur dolore error explicabo facere fugiat harum, ipsa, libero maiores minus nostrum officia praesentium qui repellendus sint voluptates. Ab adipisci doloremque eum expedita facere, magnam odit officia vitae. Accusamus accusantium, assumenda beatae deleniti ea eos expedita illo iure numquam, quam quas, quibusdam ratione voluptatem. Accusamus, alias corporis distinctio dolor eveniet fuga fugiat ipsa magnam mollitia neque nihil nobis nulla obcaecati reiciendis suscipit! Accusamus alias amet atque beatae blanditiis consequatur cum dignissimos, dolorum ea est eum ex id illum iure magnam minima nemo nihil obcaecati officiis pariatur porro provident quam repellendus reprehenderit rerum, similique sit soluta ut veniam vitae! Beatae culpa illum ipsum minus neque repudiandae sequi voluptas! Animi consequatur culpa earum officiis perspiciatis, quod ratione repellat. Asperiores at debitis ducimus exercitationem, harum hic ipsam ipsum iure magnam magni nobis perferendis quam repudiandae unde voluptatem? Autem dicta doloribus earum est ipsam itaque laudantium natus nemo pariatur suscipit. Adipisci commodi, delectus? A aut culpa cupiditate dicta ducimus est, fugit ipsam ipsum modi odio provident quaerat qui quo sunt temporibus? Culpa delectus dignissimos doloremque exercitationem id, modi qui quod reiciendis sit ut, voluptatem."
          ssh github@test.diarainfra.com "hostname"